version: 2

defaults: &defaults
  working_directory: ~/chingon
  docker:
    - image: circleci/node:10.15

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "npm-shrinkwrap.json" }}
            - v1-dependencies-
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "npm-shrinkwrap.json" }}
      - persist_to_workspace:
          root: ~/chingon
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/chingon
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/chingon/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/