version: 2
jobs:
  build:
    working_directory: ~/chingon
    branches:
        only: master
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/chingon
          paths: .
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build    
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/chingon/.npmrc
      - run:
          name: Publish package
          command: npm publish
